export default {
    name: { type: String },
    payloads: { type: Object, required: true },
    commits: { type: Array, default: [] },
    assigned: { type: Array, default: [] },
    region: { type: String, default: 0 },
    status: { type: String, default: 'pending' },
    finished: { type: Boolean, default: false },
    debtQuantity: { type: Number, default: 0 },
    quantityReached: { type: Boolean, default: false },
    producedQuantity: { type: Number, default: 0 },
    created: { type: Number, required: true },
    expired: { type: Boolean, default: false },
    workshift: { type: String },
    scheduledStart: { type: String },
    scheduledFinish: { type: String },
}